# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='shops',
            field=models.ManyToManyField(to='iShop.Shop'),
        ),
        migrations.AddField(
            model_name='seller',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 21, 32, 55, 728000)),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iShop.Shop'),
        ),
    ]
