# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iShop', '0005_auto_20160815_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 0, 56, 18, 586000)),
        ),
    ]
