# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iShop', '0008_auto_20160815_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 2, 10, 4, 690000)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iShop.Shop'),
        ),
    ]
